# Generated by Django 4.2.7 on 2024-01-21 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_business_pricing_current_cost_per_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business_Pricing',
        ),
        migrations.DeleteModel(
            name='Individual_Pricing',
        ),
    ]
