# Generated by Django 4.2.7 on 2024-01-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0008_delete_business_pricing_delete_individual_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('WO_ID', models.CharField(max_length=5000)),
                ('customer', models.CharField(max_length=5000)),
                ('job', models.CharField(max_length=5000)),
                ('contractor', models.CharField(max_length=5000)),
                ('inTime', models.CharField(max_length=5000)),
                ('outTime', models.CharField(max_length=5000)),
                ('totalTime', models.CharField(max_length=5000)),
                ('job_description', models.TextField()),
                ('waht_was_completed', models.TextField()),
                ('still_needs_completed', models.TextField()),
                ('issues', models.TextField()),
                ('signature', models.ImageField(upload_to='media/Signatures')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/Images')),
            ],
        ),
    ]
