# Generated by Django 4.2.7 on 2024-01-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_images_imagesdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='signature',
            field=models.ImageField(upload_to='Signatures'),
        ),
        migrations.AlterField(
            model_name='imagesdata',
            name='image',
            field=models.ImageField(upload_to='Images'),
        ),
    ]
